version: '2'
services:
  redis:
    image: redis:5
    container_name: parallel-worker-storage
    ports:
      - 6379:6379
  database:
    image: postgres:12-alpine
    container_name: parallel-worker-database
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    volumes:
      - database:/var/lib/postgresql/data
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  database:
